import os

DATA_CLEANING_USER = os.environ.get('DATA_CLEANING_DB_USER')
DATA_CLEANING_PASSWORD = os.environ.get('DATA_CLEANING_DB_PASS')
DATA_CLEANING_HOST = os.environ.get('DATA_CLEANING_DB_HOST')
DATA_CLEANING_PORT = os.environ.get('DATA_CLEANING_DB_PORT')
DATA_CLEANING_DATABASE = os.environ.get('DATA_CLEANING_DB_NAME')
SOURCE_SCHEMA = os.environ.get('SOURCE_SCHEMA')
SOURCE_USER = os.environ.get('SOURCE_DB_USER')
SOURCE_PASSWORD = os.environ.get('SOURCE_DB_PASS')
SOURCE_HOST = os.environ.get('SOURCE_DB_HOST')
SOURCE_PORT = os.environ.get('SOURCE_DB_PORT')
SOURCE_DATABASE = os.environ.get('SOURCE_DB_NAME')
DATA_CLEANING_SCHEMA = os.environ.get('DATA_CLEANING_SCHEMA')
