version: '3'

services:
  data-cleaning:
    container_name: data-cleaning
    build:
      context: ./data-cleaning
      dockerfile: Dockerfile
    volumes:
      - ./data-cleaning:/app

  model-consumer:
    container_name: model-consumer
    build:
      context: ./model-consumer
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
    volumes:
      - ./model-consumer:/app
    tmpfs:
      - /tmp

  model-producer:
    container_name: model-producer
    build:
      context: ./model-producer
      dockerfile: Dockerfile
    volumes:
      - ./model-producer:/app
    tmpfs:
      - /tmp
