version: '3'

services:
  data-cleaning-dev:
    container_name: data-cleaning-dev
    build:
      context: ./data-cleaning
      dockerfile: Dockerfile
    volumes:
      - ./data-cleaning:/app
    env_file:
      - env/data-cleaning/dev-cloud.env

  model-consumer-dev:
    container_name: model-consumer-dev
    build:
      context: ./model-consumer
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
    env_file:
      - ./env/model-consumer/dev-cloud.env
    volumes:
      - ./model-consumer:/app
    tmpfs:
      - /tmp

  model-producer-dev:
    container_name: model-producer-dev
    build:
      context: ./model-producer
      dockerfile: Dockerfile
    env_file:
      - ./env/model-producer/dev-cloud.env
    volumes:
      - ./model-producer:/app
    tmpfs:
      - /tmp

#  datascience-notebook:
#    container_name: jupyter
#    image: jupyter/datascience-notebook
#    volumes:
#      - ./playground:/home/jovyan/work
#    ports:
#      - "8888:8888"



