version: '3'

services:
  backend:
    container_name: backend
    build:
      context: .
    depends_on:
      - postgres_db
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    env_file:
      - ./dev.env
    networks:
      - pgnetwork

  postgres_db:
    container_name: postgres_db
    image: postgres:13.5-alpine
    ports:
      - "5438:5432"
    networks:
      - pgnetwork
    env_file:
      - ./dev.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db/init_scripts/:/docker-entrypoint-initdb.d/

  datascience-notebook:
    container_name: jupyter
    image: jupyter/datascience-notebook
    volumes:
      - ./playground:/home/jovyan/work
    ports:
      - "8888:8888"
    networks:
      - pgnetwork

networks:
  pgnetwork:
    driver: bridge



