version: '3'

services:
  data-cleaning:
    container_name: data-cleaning
    build:
      context: ./data-cleaning
      dockerfile: Dockerfile
    depends_on:
      - dev_db
      - data_cleaning_db
    volumes:
      - ./data-cleaning:/app
    env_file:
      - env/data-cleaning/dev.env
    networks:
      - app-network

  model-consumer:
    container_name: model-consumer
    build:
      context: ./model-consumer
      dockerfile: Dockerfile
    env_file:
      - ./env/model-consumer/dev.env
    volumes:
      - ./model-consumer:/app
      - ./ml-models:/app/ml-models

  model-producer:
    container_name: model-producer
    build:
      context: ./model-producer
      dockerfile: Dockerfile
    links:
      - data_cleaning_db:data_cleaning_db
    env_file:
      - ./env/model-producer/dev.env
    volumes:
      - ./model-producer:/app
      - ./ml-models:/app/ml-models
      - ./client-plots:/app/client-plots
    networks:
      - app-network

  dev_db:
    container_name: dev_db
    image: postgres:13.5-alpine
    ports:
      - "5438:5432"
    networks:
      - app-network
    env_file:
      - env/dev_db/conn.env
    volumes:
      - ./dev-db-data:/var/lib/postgresql/data
      - ./db/init_scripts_dev_db/:/docker-entrypoint-initdb.d/

  data_cleaning_db:
    container_name: data_cleaning_db
    image: postgres:13.5-alpine
    ports:
      - "5439:5432"
    networks:
      - app-network
    env_file:
      - env/data-cleaning-db/conn_dev.env
    volumes:
      - ./data-cleaning-db-data:/var/lib/postgresql/data
      - ./db/init_scripts_datacleaning_db/:/docker-entrypoint-initdb.d/

  datascience-notebook:
    container_name: jupyter
    image: jupyter/datascience-notebook
    depends_on:
      - data_cleaning_db
    volumes:
      - ./playground:/home/jovyan/work
    ports:
      - "8888:8888"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


