version: '3'

services:
  data-cleaning:
    container_name: data-cleaning-prod
    build:
      context: ./data-cleaning
      dockerfile: Dockerfile
    depends_on:
      - dev_db
      - data_cleaning_db
    volumes:
      - ./data-cleaning:/app
    env_file:
      - env/data-cleaning/prod.env
    networks:
      - app-network

  model-consumer:
    container_name: model-consumer-prod
    build:
      context: ./model-consumer
      dockerfile: Dockerfile
    depends_on:
      - data_cleaning_db
    ports:
      - "5000:5000"
    env_file:
      - ./env/model-consumer/prod.env
    volumes:
      - ./model-consumer:/app
    tmpfs:
      - /tmp
    networks:
      - app-network

  model-producer:
    container_name: model-producer-prod
    build:
      context: ./model-producer
      dockerfile: Dockerfile
    links:
      - data_cleaning_db:data_cleaning_db
    env_file:
      - ./env/model-producer/prod.env
    volumes:
      - ./model-producer:/app
    tmpfs:
      - /tmp
    networks:
      - app-network

  data_cleaning_db:
    container_name: data_cleaning_db-prod
    image: postgres:13.5-alpine
    ports:
      - "5439:5432"
    networks:
      - app-network
    env_file:
      - env/data-cleaning-db/conn_prod.env
    volumes:
      - ./data-cleaning-db-data:/var/lib/postgresql/data
      - ./db/init_scripts_datacleaning_db/:/docker-entrypoint-initdb.d/

networks:
  app-network:
    driver: bridge