version: 1
disable_existing_loggers: true

formatters:
  error:
    format: '%(asctime)s-%(levelname)s-%(name)s-%(process)d::%(module)s|%(lineno)s::
      %(message)s'
  info:
    format: '%(asctime)s-%(levelname)s-%(name)s::%(module)s|%(lineno)s:: %(message)s'

handlers:
  debug_console_handler:
    class: logging.StreamHandler
    formatter: info
    level: DEBUG
    stream: ext://sys.stdout

  error_file_handler:
    backupCount: 1
    class: logging.handlers.RotatingFileHandler
    filename: tmp/error.log
    formatter: error
    level: ERROR
    maxBytes: 1048576
    mode: a

  info_rotating_file_handler:
    backupCount: 1
    class: logging.handlers.RotatingFileHandler
    filename: tmp/info.log
    formatter: info
    level: INFO
    maxBytes: 1048576
    mode: a

root:
  handlers: [debug_console_handler, info_rotating_file_handler, error_file_handler]
  level: NOTSET

loggers:
  appLog:
    handlers: [debug_console_handler, info_rotating_file_handler, error_file_handler]
    level: INFO
    propagate: false
