version: 1
disable_existing_loggers: False
formatters:
  json:
    format: "[%(asctime)s] %(process)d %(levelname)s %(name)s:%(funcName)s:%(lineno)s - %(message)s"
  plaintext:
    format: "[%(asctime)s] %(process)d %(levelname)s %(name)s:%(funcName)s:%(lineno)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    formatter: plaintext
    level: DEBUG
    stream: ext://sys.stdout
  logfile:
    class: logging.handlers.RotatingFileHandler
    formatter: plaintext
    level: DEBUG
    filename: tmp/staticlog.log
    maxBytes: 10000
    backupCount: 1
root:
  level: DEBUG
  propagate: True
  handlers: [console, logfile]
loggers:
  appLog:
    andlers: [console, logfile]
    level: INFO
  botocore:
    level: INFO
  urllib3:
    level: INFO