CREATE TABLE machine_learning.cleaned_aggregated_data
(
    id                               BIGSERIAL PRIMARY KEY,
    ad_client_id                     bigint                       not null,
    ad_org_id                        bigint                       not null,
    dateinvoiced                     timestamp(0)                 not null,
    c_bpartner_id                    bigint                       not null,
    c_invoice_id                     varchar                      not null,
    c_bpartner_location_id           bigint                       not null,
    paymentrule                      char                         not null,
    grandtotal                       numeric default (0)::numeric not null,
    duedate                          timestamp(0),
    totalopenamt                     numeric default (0)::numeric not null,
    paidamt                          numeric default (0)::numeric not null,
    datetrx                          timestamp(0),
    tendertype                       char,
    allocatedamt                     numeric default (0)::numeric,
    c_allocationline_id              bigint,
    dayslate                         numeric,
    daystosettle                     numeric,
    late                             numeric(1) check (late = 1 or late = 0),
    paid                             numeric(1) check (paid = 1 or paid = 0),
    closed_invoices_no               bigint,
    closed_late_invoice              numeric(1) check (closed_late_invoice = 1 or closed_late_invoice = 0),
    closed_late_invoices_no          bigint,
    paid_late_percent                numeric,
    paid_total                       numeric,
    paid_late_sum                    numeric,
    paid_late_total                  numeric,
    total_invoices                   bigint,
    late_unpaid_invoices_percent     numeric,
    late_unpaid_invoices_sum_percent numeric,
    paid_late_raport_percent         numeric,
    days_late_closed_invoices_late   bigint,
    avg_days_paid_late               numeric,
    unpaid_invoices_no               bigint,
    invoice_late_unpaid              numeric(1),
    late_unpaid_invoices_no          bigint,
    unpaid_sum                       numeric,
    unpaid_invoices_sum              numeric,
    unpaid_late_sum                  numeric,
    unpaid_invoices_late_sum         numeric,
    max_paid                         numeric,
    min_paid                         numeric,
    avg_paid                         numeric,
    std_paid                         numeric,
    max_late_paid                    numeric,
    min_late_paid                    numeric,
    avg_late_paid                    numeric,
    std_late_paid                    numeric,
    max_unpaid                       numeric,
    min_unpaid                       numeric,
    avg_unpaid                       numeric,
    std_unpaid                       numeric,
    max_late_unpaid                  numeric,
    min_late_unpaid                  numeric,
    avg_late_unpaid                  numeric,
    std_late_unpaid                  numeric
);

CREATE INDEX ad_client_idx ON machine_learning.cleaned_aggregated_data (ad_client_id);

CREATE INDEX c_bpartner_idx ON machine_learning.cleaned_aggregated_data (c_bpartner_id)
