version: 1
disable_existing_loggers: true

formatters:
  error:
    format: '%(asctime)s-%(levelname)s-%(name)s-%(process)d::%(module)s|%(lineno)s::
      %(message)s'
  info:
    format: '%(asctime)s-%(levelname)s-%(name)s::%(module)s|%(lineno)s:: %(message)s'
  jsonFormat:
    format: '{ "loggerName": "%(name)s", "asciTime": "%(asctime)s", "fileName": "%(filename)s", "logRecordCreationTime": "%(created)f", "functionName": "%(funcName)s", "levelNo": "%(levelno)s", "lineNo": "%(lineno)d", "time": "%(msecs)d", "levelName": "%(levelname)s", "message": "%(message)s" }'

filters:
  show_info_only:
    (): utils.log.InfoFilter


handlers:
  debug_console_handler:
    class: logging.StreamHandler
    formatter: info
    level: DEBUG
    stream: ext://sys.stdout

  error_file_handler:
    backupCount: 1
    class: logging.handlers.RotatingFileHandler
    filename: tmp/error.log
    formatter: error
    level: ERROR
    maxBytes: 1048576
    mode: a

  info_rotating_file_handler:
    backupCount: 1
    class: logging.handlers.RotatingFileHandler
    filename: tmp/info.log
    formatter: info
    level: INFO
    maxBytes: 1048576
    mode: a

  server_rotating_file_handler:
    backupCount: 1
    class: logging.handlers.RotatingFileHandler
    filename: tmp/server_werkzeug.log
    formatter: info
    level: DEBUG
    maxBytes: 1048576
    mode: a

  handler_HTTPSHandler:
    class: loggly.handlers.HTTPSHandler
    formatter: jsonFormat
    level: INFO
    url: ${LOGGLY_URL}
    filters: [show_info_only]

root:
  handlers: [ debug_console_handler, info_rotating_file_handler, error_file_handler ]
  level: NOTSET

loggers:
  modelConsumerLog:
    handlers: [ debug_console_handler, info_rotating_file_handler, error_file_handler, handler_HTTPSHandler ]
    level: INFO
    propagate: false

  werkzeug:
    handlers: [ debug_console_handler, server_rotating_file_handler ]
    level: DEBUG
    propagate: false